### PR TITLE
JSON::XS -> JSON::MaybeXS (closes #30)

### LINKED ISSUE #30: JSON::XS -> JSON::MaybeXS
..to conform to best practices.
I can send a PR if you like.

### PR DESCRIPTION
**Pull request by karenetheridge**

### CODE REVIEW

**Review by Integralist — APPROVED** [review]
@karenetheridge the changes look fine, but could you please provide some more context in the PR description as to why we're making this change and what the side-effects (if any) are. Thanks.

**Comment by karenetheridge** [comment]
JSON::XS's author refuses to use public bugtracking and actively breaks interoperability. Cpanel::JSON::XS is a fork with several bugfixes and a more collaborative maintainer. JSON::MaybeXS uses Cpanel::JSON::XS when available, and falls back to JSON::PP (in core) otherwise.

**Comment by Integralist** [comment]
Thanks @karenetheridge for the clarification 👍🏻 

As this is a drop-in replacement I feel more confident merging this PR.

I'm not aware of any release process for this API client though, so I'm not sure if it's supposed to be distributed to a module registry?

**Comment by karenetheridge** [comment]
It's released to cpan -- https://metacpan.org/dist/Net-Fastly -- but I don't know who has the keys to the account. No doubt @miyagawa knows :)

**Comment by plicease** [comment]
This gets released when taged, but it is setup to do this in Travis-CI so we should update this to do the same in Jenkins.

**Comment by Integralist** [comment]
Closing because it's superseded by https://github.com/fastly/fastly-perl/pull/33 which is a code-generated client.

**Pull request closed without merging**
