### PR TITLE
Add user agent headers to _headers

### PR DESCRIPTION
**Pull request by gschorkopf**
Risks
`¯\_(ツ)_/¯`

### CODE REVIEW

**Comment by drbrain** [comment]
IIRC this was OK'd by @miyagawa

**Comment by drbrain** [comment]
Found OK by @miyagawa: https://fastly.slack.com/archives/team-features/p1463774547002348

**Comment by drbrain** [comment]
My name is Eric Hodel and I approve this pull request

**Comment by gschorkopf** [comment]
Now... how do we release this?

**Pull request merged**
